build: .
volumes:
   - .:/code
ports:
   - 8000:8000
expose:
   - 8000
links:
   - redis:redis 
# user: "1000:1000"
command: python /code/myproj/manage.py runserver 0.0.0.0:8000

redis:
   image: redis
   expose:
    - 6379

nginx:
   restart: always
   build: ./nginx/
   depends_on:
       - web
   ports:
       - "80:80"
      # - "443:443"
#     volumes:
#        - ./myproj/myapp/static:/static
links:
    - web:web 