#adapted from example in docker documentation
version: '3'

services:
  web:
    build: .
    volumes:
       - .:/code
    expose:
       - 8000
    environment:
       - GOOGLE_APPLICATION_CREDENTIALS=/code/myproj/My First Project-9b409ea0537e.json
    links:
       - redis:redis 
    # user: "1000:1000"
    command: python /code/myproj/manage.py runserver 0.0.0.0:8000

  redis:
    image: redis
    expose:
        - 6379
