#adapted from example in docker documentation
version: '3'

services:
  web:
    build: .
    volumes:
       - .:/code
    expose:
       - 8000
    command: python /code/myproj/manage.py runserver 0.0.0.0:8000