# Generated by Django 3.0.5 on 2020-04-18 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipe',
            new_name='Recipe_model',
        ),
    ]
