# Generated by Django 3.0.5 on 2020-04-19 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20200418_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_model',
            name='description',
            field=models.TextField(default='Enter a description here'),
        ),
        migrations.AlterField(
            model_name='recipe_model',
            name='ingredients',
            field=models.TextField(default='Enter ingredients here'),
        ),
        migrations.AlterField(
            model_name='recipe_model',
            name='title',
            field=models.CharField(max_length=180),
        ),
    ]
