# Generated by Django 3.0.5 on 2020-04-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20200419_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe_model',
            name='cook_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
