# Generated by Django 3.0.5 on 2020-04-27 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
