# Generated by Django 3.0.5 on 2020-04-28 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
