# Generated by Django 3.0.5 on 2020-05-07 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0014_auto_20200506_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe_model',
            name='images',
            field=models.ImageField(blank=True, upload_to='recipe_image'),
        ),
    ]
