# Generated by Django 3.0.5 on 2020-05-07 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0015_recipe_model_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_model',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
