# Generated by Django 3.0.5 on 2020-05-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0017_auto_20200507_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_model',
            name='images',
            field=models.ImageField(blank=True, default='noimage.png', upload_to='recipe_image/'),
        ),
    ]
