# Generated by Django 3.0.5 on 2020-05-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0019_auto_20200507_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_model',
            name='images',
            field=models.ImageField(blank=True, upload_to='recipe/image'),
        ),
    ]
