# Generated by Django 3.0.5 on 2020-05-10 22:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0020_auto_20200509_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe_model',
            name='servings',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='recipe_model',
            name='cook_time',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(720)]),
        ),
    ]
