# Generated by Django 3.0.5 on 2020-05-11 16:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0022_auto_20200511_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe_model',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
