# Generated by Django 3.0.5 on 2020-05-11 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0023_recipe_model_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe_model',
            name='likes',
        ),
    ]
