# Generated by Django 3.0.5 on 2020-05-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0024_remove_recipe_model_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_model',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
