# Generated by Django 3.0.5 on 2020-05-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0025_auto_20200511_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_model',
            name='description',
            field=models.TextField(blank=True, default='Enter a description here', null=True),
        ),
        migrations.AlterField(
            model_name='recipe_model',
            name='ingredients',
            field=models.TextField(blank=True, default='Enter ingredients here', null=True),
        ),
        migrations.AlterField(
            model_name='recipe_model',
            name='title',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
