# Generated by Django 3.0.6 on 2020-05-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0031_auto_20200513_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=80)),
            ],
        ),
    ]
