# Generated by Django 3.0.6 on 2020-05-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0032_topic_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic_model',
            name='topic',
            field=models.CharField(max_length=100),
        ),
    ]
