# Generated by Django 3.0.6 on 2020-05-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0033_auto_20200514_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_model',
            name='images',
            field=models.ImageField(blank=True, default='media/noimage.png', null=True, upload_to='recipe/image'),
        ),
    ]
