# Generated by Django 3.0.6 on 2020-05-15 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0036_auto_20200514_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic_model',
            old_name='topic',
            new_name='public_topic',
        ),
    ]
